var a1 = </>;
var a2 = <a: />;
var a3 = <:a />;
var a4 = <a b=d />;
var a5 = <a>;
var a6 = <a></b>;
var a7 = <a foo="bar;
var a8 = <a:b></b>;
var a9 = <a:b.c></a:b.c>;
var a10 = <a.b:c></a.b:c>;
var a11 = <a.b.c></a>;
var a12 = <.a></.a>;
var a13 = <a.></a.>;
var a14 = <a[foo]></a[foo]>;
var a15 = <a[\'foo\']></a[\'foo\']>;
var a16 = <a><a />;
var a17 = <a b={}>;
var a18 = var x = <div>one</div><div>two</div>;;
var a19 = var x = <div>one</div> /* intervening comment */ <div>two</div>;;
var a20 = <a>{"str";}</a>;
var a21 = <span className="a", id="b" />;
var a22 = <div className"app">;
var a23 = <div {props} />;
var a24 = <div>stuff</div {...props}>;
var a25 = <div {...props}>stuff</div {...props}>;
var a26 = <a>></a>;
var a27 = <a> ></a>;
var a28 = <a b=}>;
var a29 = <a b=<}>;
var a30 = <a>}</a>;
var a31 = <a .../*hai*/asdf/>;